//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SolAR.Api.Image {

    using XPCF.Api;
    using SolAR.Core;
    using SolAR.Datastructure;

public class IImageConvertor : IComponentIntrospect {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal IImageConvertor(global::System.IntPtr cPtr, bool cMemoryOwn) : base(solar_api_imagePINVOKE.IImageConvertor_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IImageConvertor obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IImageConvertor() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          solar_api_imagePINVOKE.delete_IImageConvertor(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public virtual FrameworkReturnCode convert(Image imgSrc, Image imgDst) {
    FrameworkReturnCode ret = (FrameworkReturnCode)solar_api_imagePINVOKE.IImageConvertor_convert__SWIG_0(swigCPtr, Image.getCPtr(imgSrc), Image.getCPtr(imgDst));
    if (solar_api_imagePINVOKE.SWIGPendingException.Pending) throw solar_api_imagePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual FrameworkReturnCode convert(Image imgSrc, Image imgDst, Image.ImageLayout destLayout) {
    FrameworkReturnCode ret = (FrameworkReturnCode)solar_api_imagePINVOKE.IImageConvertor_convert__SWIG_1(swigCPtr, Image.getCPtr(imgSrc), Image.getCPtr(imgDst), (int)destLayout);
    if (solar_api_imagePINVOKE.SWIGPendingException.Pending) throw solar_api_imagePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
