//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SolAR.Core {


public class CharList : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IList<string>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CharList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CharList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CharList() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          solar_corePINVOKE.delete_CharList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public CharList(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (string element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public string this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(string[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(string[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, string[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<string> global::System.Collections.Generic.IEnumerable<string>.GetEnumerator() {
    return new CharListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new CharListEnumerator(this);
  }

  public CharListEnumerator GetEnumerator() {
    return new CharListEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class CharListEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<string>
  {
    private CharList collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public CharListEnumerator(CharList collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public string Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (string)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    solar_corePINVOKE.CharList_Clear(swigCPtr);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(string x) {
    solar_corePINVOKE.CharList_Add(swigCPtr, x);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = solar_corePINVOKE.CharList_size(swigCPtr);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = solar_corePINVOKE.CharList_capacity(swigCPtr);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    solar_corePINVOKE.CharList_reserve(swigCPtr, n);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public CharList() : this(solar_corePINVOKE.new_CharList__SWIG_0(), true) {
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public CharList(CharList other) : this(solar_corePINVOKE.new_CharList__SWIG_1(CharList.getCPtr(other)), true) {
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public CharList(int capacity) : this(solar_corePINVOKE.new_CharList__SWIG_2(capacity), true) {
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  private string getitemcopy(int index) {
    string ret = solar_corePINVOKE.CharList_getitemcopy(swigCPtr, index);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private string getitem(int index) {
    string ret = solar_corePINVOKE.CharList_getitem(swigCPtr, index);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, string val) {
    solar_corePINVOKE.CharList_setitem(swigCPtr, index, val);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(CharList values) {
    solar_corePINVOKE.CharList_AddRange(swigCPtr, CharList.getCPtr(values));
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public CharList GetRange(int index, int count) {
    global::System.IntPtr cPtr = solar_corePINVOKE.CharList_GetRange(swigCPtr, index, count);
    CharList ret = (cPtr == global::System.IntPtr.Zero) ? null : new CharList(cPtr, true);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, string x) {
    solar_corePINVOKE.CharList_Insert(swigCPtr, index, x);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, CharList values) {
    solar_corePINVOKE.CharList_InsertRange(swigCPtr, index, CharList.getCPtr(values));
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    solar_corePINVOKE.CharList_RemoveAt(swigCPtr, index);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    solar_corePINVOKE.CharList_RemoveRange(swigCPtr, index, count);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public static CharList Repeat(string value, int count) {
    global::System.IntPtr cPtr = solar_corePINVOKE.CharList_Repeat(value, count);
    CharList ret = (cPtr == global::System.IntPtr.Zero) ? null : new CharList(cPtr, true);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    solar_corePINVOKE.CharList_Reverse__SWIG_0(swigCPtr);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    solar_corePINVOKE.CharList_Reverse__SWIG_1(swigCPtr, index, count);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, CharList values) {
    solar_corePINVOKE.CharList_SetRange(swigCPtr, index, CharList.getCPtr(values));
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(string value) {
    bool ret = solar_corePINVOKE.CharList_Contains(swigCPtr, value);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int IndexOf(string value) {
    int ret = solar_corePINVOKE.CharList_IndexOf(swigCPtr, value);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int LastIndexOf(string value) {
    int ret = solar_corePINVOKE.CharList_LastIndexOf(swigCPtr, value);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Remove(string value) {
    bool ret = solar_corePINVOKE.CharList_Remove(swigCPtr, value);
    if (solar_corePINVOKE.SWIGPendingException.Pending) throw solar_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
