//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SolAR.Core {

public enum FrameworkReturnCode {
  _STOP = 1,
  _SUCCESS = 0,
  _ERROR_ = -1,
  _ERROR_LOAD_IMAGE = -10,
  _ERROR_ACCESS_IMAGE = -11
}

}
