//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SolAR.Api.Input.Files {

    using XPCF.Api;
    using SolAR.Core;
    using SolAR.Datastructure;

public class IMarker2DSquared : IMarker {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal IMarker2DSquared(global::System.IntPtr cPtr, bool cMemoryOwn) : base(solar_api_input_filesPINVOKE.IMarker2DSquared_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IMarker2DSquared obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IMarker2DSquared() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          solar_api_input_filesPINVOKE.delete_IMarker2DSquared(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public void setSize(float width, float height) {
    solar_api_input_filesPINVOKE.IMarker2DSquared_setSize(swigCPtr, width, height);
    if (solar_api_input_filesPINVOKE.SWIGPendingException.Pending) throw solar_api_input_filesPINVOKE.SWIGPendingException.Retrieve();
  }

  public float getWidth() {
    float ret = solar_api_input_filesPINVOKE.IMarker2DSquared_getWidth(swigCPtr);
    if (solar_api_input_filesPINVOKE.SWIGPendingException.Pending) throw solar_api_input_filesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float getHeight() {
    float ret = solar_api_input_filesPINVOKE.IMarker2DSquared_getHeight(swigCPtr);
    if (solar_api_input_filesPINVOKE.SWIGPendingException.Pending) throw solar_api_input_filesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Sizef getSize() {
    Sizef ret = new Sizef(solar_api_input_filesPINVOKE.IMarker2DSquared_getSize(swigCPtr), true);
    if (solar_api_input_filesPINVOKE.SWIGPendingException.Pending) throw solar_api_input_filesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual FrameworkReturnCode getImageCorners(Point2DfList imageCorners) {
    FrameworkReturnCode ret = (FrameworkReturnCode)solar_api_input_filesPINVOKE.IMarker2DSquared_getImageCorners(swigCPtr, Point2DfList.getCPtr(imageCorners));
    if (solar_api_input_filesPINVOKE.SWIGPendingException.Pending) throw solar_api_input_filesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual FrameworkReturnCode getWorldCorners(Point3DfList worldCorners) {
    FrameworkReturnCode ret = (FrameworkReturnCode)solar_api_input_filesPINVOKE.IMarker2DSquared_getWorldCorners(swigCPtr, Point3DfList.getCPtr(worldCorners));
    if (solar_api_input_filesPINVOKE.SWIGPendingException.Pending) throw solar_api_input_filesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
