//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XPCF.Component {

    using XPCF.Core;
    using XPCF.Api;

public class ComponentBase : IComponentIntrospect {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal ComponentBase(global::System.IntPtr cPtr, bool cMemoryOwn) : base(xpcf_componentPINVOKE.ComponentBase_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ComponentBase obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ComponentBase() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          xpcf_componentPINVOKE.delete_ComponentBase(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public UUID getUUID() {
    UUID ret = new UUID(xpcf_componentPINVOKE.ComponentBase_getUUID(swigCPtr), false);
    if (xpcf_componentPINVOKE.SWIGPendingException.Pending) throw xpcf_componentPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void unloadComponent() {
    xpcf_componentPINVOKE.ComponentBase_unloadComponent(swigCPtr);
    if (xpcf_componentPINVOKE.SWIGPendingException.Pending) throw xpcf_componentPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
