//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XPCF.Core {


public class Exception : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Exception(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Exception obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Exception() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xpcf_corePINVOKE.delete_Exception(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Exception(XPCFErrorCode errCode) : this(xpcf_corePINVOKE.new_Exception__SWIG_0((int)errCode), true) {
    if (xpcf_corePINVOKE.SWIGPendingException.Pending) throw xpcf_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public Exception(string what, XPCFErrorCode errCode) : this(xpcf_corePINVOKE.new_Exception__SWIG_1(what, (int)errCode), true) {
    if (xpcf_corePINVOKE.SWIGPendingException.Pending) throw xpcf_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public Exception(string what) : this(xpcf_corePINVOKE.new_Exception__SWIG_2(what), true) {
    if (xpcf_corePINVOKE.SWIGPendingException.Pending) throw xpcf_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public XPCFErrorCode getErrorCode() {
    XPCFErrorCode ret = (XPCFErrorCode)xpcf_corePINVOKE.Exception_getErrorCode(swigCPtr);
    if (xpcf_corePINVOKE.SWIGPendingException.Pending) throw xpcf_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
