//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XPCF.Core {


public class InterfaceNotImplementedException : Exception {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal InterfaceNotImplementedException(global::System.IntPtr cPtr, bool cMemoryOwn) : base(xpcf_corePINVOKE.InterfaceNotImplementedException_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(InterfaceNotImplementedException obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~InterfaceNotImplementedException() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xpcf_corePINVOKE.delete_InterfaceNotImplementedException(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public InterfaceNotImplementedException(UUID componentUUID, UUID interfaceUUID) : this(xpcf_corePINVOKE.new_InterfaceNotImplementedException__SWIG_0(UUID.getCPtr(componentUUID), UUID.getCPtr(interfaceUUID)), true) {
    if (xpcf_corePINVOKE.SWIGPendingException.Pending) throw xpcf_corePINVOKE.SWIGPendingException.Retrieve();
  }

  public InterfaceNotImplementedException(string what) : this(xpcf_corePINVOKE.new_InterfaceNotImplementedException__SWIG_1(what), true) {
    if (xpcf_corePINVOKE.SWIGPendingException.Pending) throw xpcf_corePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
