//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SolAR.Api.Solver.Map {

    using XPCF.Api;
    using SolAR.Core;
    using SolAR.Datastructure;

public class PairUIntUInt : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PairUIntUInt(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PairUIntUInt obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PairUIntUInt() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          solar_api_solver_mapPINVOKE.delete_PairUIntUInt(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PairUIntUInt() : this(solar_api_solver_mapPINVOKE.new_PairUIntUInt__SWIG_0(), true) {
    if (solar_api_solver_mapPINVOKE.SWIGPendingException.Pending) throw solar_api_solver_mapPINVOKE.SWIGPendingException.Retrieve();
  }

  public PairUIntUInt(uint t, uint u) : this(solar_api_solver_mapPINVOKE.new_PairUIntUInt__SWIG_1(t, u), true) {
    if (solar_api_solver_mapPINVOKE.SWIGPendingException.Pending) throw solar_api_solver_mapPINVOKE.SWIGPendingException.Retrieve();
  }

  public PairUIntUInt(PairUIntUInt p) : this(solar_api_solver_mapPINVOKE.new_PairUIntUInt__SWIG_2(PairUIntUInt.getCPtr(p)), true) {
    if (solar_api_solver_mapPINVOKE.SWIGPendingException.Pending) throw solar_api_solver_mapPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint first {
    set {
      solar_api_solver_mapPINVOKE.PairUIntUInt_first_set(swigCPtr, value);
      if (solar_api_solver_mapPINVOKE.SWIGPendingException.Pending) throw solar_api_solver_mapPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      uint ret = solar_api_solver_mapPINVOKE.PairUIntUInt_first_get(swigCPtr);
      if (solar_api_solver_mapPINVOKE.SWIGPendingException.Pending) throw solar_api_solver_mapPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public uint second {
    set {
      solar_api_solver_mapPINVOKE.PairUIntUInt_second_set(swigCPtr, value);
      if (solar_api_solver_mapPINVOKE.SWIGPendingException.Pending) throw solar_api_solver_mapPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      uint ret = solar_api_solver_mapPINVOKE.PairUIntUInt_second_get(swigCPtr);
      if (solar_api_solver_mapPINVOKE.SWIGPendingException.Pending) throw solar_api_solver_mapPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}

}
