//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XPCF.Properties {

    using XPCF.Core;
    using XPCF.Collection;

public class IProperty : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal IProperty(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IProperty obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IProperty() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          xpcf_propertiesPINVOKE.delete_IProperty(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual string getName() {
    string ret = xpcf_propertiesPINVOKE.IProperty_getName(swigCPtr);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual IProperty.PropertyType getType() {
    IProperty.PropertyType ret = (IProperty.PropertyType)xpcf_propertiesPINVOKE.IProperty_getType(swigCPtr);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual XPCFErrorCode copyTo(IProperty dest) {
    XPCFErrorCode ret = (XPCFErrorCode)xpcf_propertiesPINVOKE.IProperty_copyTo(swigCPtr, IProperty.getCPtr(dest));
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setName(string name) {
    xpcf_propertiesPINVOKE.IProperty_setName(swigCPtr, name);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual uint size() {
    uint ret = xpcf_propertiesPINVOKE.IProperty_size(swigCPtr);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setIntegerValue(int val, uint itemIndex) {
    xpcf_propertiesPINVOKE.IProperty_setIntegerValue__SWIG_0(swigCPtr, val, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setIntegerValue(int val) {
    xpcf_propertiesPINVOKE.IProperty_setIntegerValue__SWIG_1(swigCPtr, val);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setUnsignedIntegerValue(uint val, uint itemIndex) {
    xpcf_propertiesPINVOKE.IProperty_setUnsignedIntegerValue__SWIG_0(swigCPtr, val, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setUnsignedIntegerValue(uint val) {
    xpcf_propertiesPINVOKE.IProperty_setUnsignedIntegerValue__SWIG_1(swigCPtr, val);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setLongValue(long val, uint itemIndex) {
    xpcf_propertiesPINVOKE.IProperty_setLongValue__SWIG_0(swigCPtr, val, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setLongValue(long val) {
    xpcf_propertiesPINVOKE.IProperty_setLongValue__SWIG_1(swigCPtr, val);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setUnsignedLongValue(ulong val, uint itemIndex) {
    xpcf_propertiesPINVOKE.IProperty_setUnsignedLongValue__SWIG_0(swigCPtr, val, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setUnsignedLongValue(ulong val) {
    xpcf_propertiesPINVOKE.IProperty_setUnsignedLongValue__SWIG_1(swigCPtr, val);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setFloatingValue(float val, uint itemIndex) {
    xpcf_propertiesPINVOKE.IProperty_setFloatingValue__SWIG_0(swigCPtr, val, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setFloatingValue(float val) {
    xpcf_propertiesPINVOKE.IProperty_setFloatingValue__SWIG_1(swigCPtr, val);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setDoubleValue(double val, uint itemIndex) {
    xpcf_propertiesPINVOKE.IProperty_setDoubleValue__SWIG_0(swigCPtr, val, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setDoubleValue(double val) {
    xpcf_propertiesPINVOKE.IProperty_setDoubleValue__SWIG_1(swigCPtr, val);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setStringValue(string val, uint itemIndex) {
    xpcf_propertiesPINVOKE.IProperty_setStringValue__SWIG_0(swigCPtr, val, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setStringValue(string val) {
    xpcf_propertiesPINVOKE.IProperty_setStringValue__SWIG_1(swigCPtr, val);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setUnicodeStringValue(string val, uint itemIndex) {
    xpcf_propertiesPINVOKE.IProperty_setUnicodeStringValue__SWIG_0(swigCPtr, val, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setUnicodeStringValue(string val) {
    xpcf_propertiesPINVOKE.IProperty_setUnicodeStringValue__SWIG_1(swigCPtr, val);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setStructureValue(IPropertyMap val, uint itemIndex) {
    xpcf_propertiesPINVOKE.IProperty_setStructureValue__SWIG_0(swigCPtr, IPropertyMap.getCPtr(val), itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setStructureValue(IPropertyMap val) {
    xpcf_propertiesPINVOKE.IProperty_setStructureValue__SWIG_1(swigCPtr, IPropertyMap.getCPtr(val));
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual IPropertyMap getStructureValue(uint itemIndex) {
    global::System.IntPtr cPtr = xpcf_propertiesPINVOKE.IProperty_getStructureValue__SWIG_0(swigCPtr, itemIndex);
    IPropertyMap ret = (cPtr == global::System.IntPtr.Zero) ? null : new IPropertyMap(cPtr, true);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual IPropertyMap getStructureValue() {
    global::System.IntPtr cPtr = xpcf_propertiesPINVOKE.IProperty_getStructureValue__SWIG_1(swigCPtr);
    IPropertyMap ret = (cPtr == global::System.IntPtr.Zero) ? null : new IPropertyMap(cPtr, true);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual XPCFErrorCode setProperties(string name, uint numberOfValues, IProperty.AccessSpecifier iotype) {
    XPCFErrorCode ret = (XPCFErrorCode)xpcf_propertiesPINVOKE.IProperty_setProperties__SWIG_0(swigCPtr, name, numberOfValues, (int)iotype);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual XPCFErrorCode setProperties(string name, uint numberOfValues) {
    XPCFErrorCode ret = (XPCFErrorCode)xpcf_propertiesPINVOKE.IProperty_setProperties__SWIG_1(swigCPtr, name, numberOfValues);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual XPCFErrorCode setProperties(string name) {
    XPCFErrorCode ret = (XPCFErrorCode)xpcf_propertiesPINVOKE.IProperty_setProperties__SWIG_2(swigCPtr, name);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int getIntegerValue(uint itemIndex) {
    int ret = xpcf_propertiesPINVOKE.IProperty_getIntegerValue__SWIG_0(swigCPtr, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int getIntegerValue() {
    int ret = xpcf_propertiesPINVOKE.IProperty_getIntegerValue__SWIG_1(swigCPtr);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual uint getUnsignedIntegerValue(uint itemIndex) {
    uint ret = xpcf_propertiesPINVOKE.IProperty_getUnsignedIntegerValue__SWIG_0(swigCPtr, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual uint getUnsignedIntegerValue() {
    uint ret = xpcf_propertiesPINVOKE.IProperty_getUnsignedIntegerValue__SWIG_1(swigCPtr);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual long getLongValue(uint itemIndex) {
    long ret = xpcf_propertiesPINVOKE.IProperty_getLongValue__SWIG_0(swigCPtr, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual long getLongValue() {
    long ret = xpcf_propertiesPINVOKE.IProperty_getLongValue__SWIG_1(swigCPtr);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual ulong getUnsignedLongValue(uint arg0) {
    ulong ret = xpcf_propertiesPINVOKE.IProperty_getUnsignedLongValue(swigCPtr, arg0);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string getStringValue(uint itemIndex) {
    string ret = xpcf_propertiesPINVOKE.IProperty_getStringValue__SWIG_0(swigCPtr, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string getStringValue() {
    string ret = xpcf_propertiesPINVOKE.IProperty_getStringValue__SWIG_1(swigCPtr);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string getUnicodeStringValue(uint itemIndex) {
    string ret = global::System.Runtime.InteropServices.Marshal.PtrToStringUni(xpcf_propertiesPINVOKE.IProperty_getUnicodeStringValue__SWIG_0(swigCPtr, itemIndex));
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string getUnicodeStringValue() {
    string ret = global::System.Runtime.InteropServices.Marshal.PtrToStringUni(xpcf_propertiesPINVOKE.IProperty_getUnicodeStringValue__SWIG_1(swigCPtr));
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual float getFloatingValue(uint itemIndex) {
    float ret = xpcf_propertiesPINVOKE.IProperty_getFloatingValue__SWIG_0(swigCPtr, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual float getFloatingValue() {
    float ret = xpcf_propertiesPINVOKE.IProperty_getFloatingValue__SWIG_1(swigCPtr);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double getDoubleValue(uint itemIndex) {
    double ret = xpcf_propertiesPINVOKE.IProperty_getDoubleValue__SWIG_0(swigCPtr, itemIndex);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double getDoubleValue() {
    double ret = xpcf_propertiesPINVOKE.IProperty_getDoubleValue__SWIG_1(swigCPtr);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setAccessSpecifier(IProperty.AccessSpecifier iotype) {
    xpcf_propertiesPINVOKE.IProperty_setAccessSpecifier(swigCPtr, (int)iotype);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual IProperty.AccessSpecifier getAccessSpecifier() {
    IProperty.AccessSpecifier ret = (IProperty.AccessSpecifier)xpcf_propertiesPINVOKE.IProperty_getAccessSpecifier(swigCPtr);
    if (xpcf_propertiesPINVOKE.SWIGPendingException.Pending) throw xpcf_propertiesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public enum PropertyType {
    IProperty_NONE = 0,
    IProperty_INTEGER,
    IProperty_UINTEGER,
    IProperty_LONG,
    IProperty_ULONG,
    IProperty_CHARSTR,
    IProperty_UNICODESTR,
    IProperty_FLOAT,
    IProperty_DOUBLE,
    IProperty_STRUCTURE
  }

  public enum AccessSpecifier {
    IProperty_IN = 0x01,
    IProperty_OUT = 0x02,
    IProperty_INOUT = 0x04
  }

}

}
