//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XPCF.Collection {

	using System.Collections;
	using System.Collections.Generic;
	using XPCF.Core;
	using XPCF.Api;
	using XPCF.Properties;

public class InterfaceMetadataEnumerator : global::System.IDisposable, IEnumerator<InterfaceMetadata> {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal InterfaceMetadataEnumerator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(InterfaceMetadataEnumerator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~InterfaceMetadataEnumerator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          xpcf_collectionPINVOKE.delete_InterfaceMetadataEnumerator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool MoveNext() {
    bool ret = xpcf_collectionPINVOKE.InterfaceMetadataEnumerator_MoveNext(swigCPtr);
    if (xpcf_collectionPINVOKE.SWIGPendingException.Pending) throw xpcf_collectionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void Reset() {
    xpcf_collectionPINVOKE.InterfaceMetadataEnumerator_Reset(swigCPtr);
    if (xpcf_collectionPINVOKE.SWIGPendingException.Pending) throw xpcf_collectionPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual InterfaceMetadata current() {
    global::System.IntPtr cPtr = xpcf_collectionPINVOKE.InterfaceMetadataEnumerator_current(swigCPtr);
    InterfaceMetadata ret = (cPtr == global::System.IntPtr.Zero) ? null : new InterfaceMetadata(cPtr, true);
    if (xpcf_collectionPINVOKE.SWIGPendingException.Pending) throw xpcf_collectionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool endReached() {
    bool ret = xpcf_collectionPINVOKE.InterfaceMetadataEnumerator_endReached(swigCPtr);
    if (xpcf_collectionPINVOKE.SWIGPendingException.Pending) throw xpcf_collectionPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

		public InterfaceMetadata Current { get { return current(); } }
		object IEnumerator.Current { get { return current(); } }
	
}

}
