//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SolAR.Api.Features {

public enum RetCode {
  DESCRIPTORS_MATCHER_OK = 0,
  DESCRIPTORS_DONT_MATCH,
  DESCRIPTOR_TYPE_UNDEFINED,
  DESCRIPTOR_EMPTY
}

}
